# Generated by Django 4.2 on 2025-12-05 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_recurringtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
